#!/usr/bin/env bash
set -euo pipefail

DOTFILES_REPO="${DOTFILES_REPO:-https://github.com/mxvoloshin/dotfiles.git}"
DOTFILES_DIR="${HOME}/.dotfiles"

log() { echo "[dotfiles-sync] $*"; }

safe_append_once() {
  local file="$1"
  local marker="$2"
  local content="$3"

  touch "${file}"
  if ! grep -q "${marker}" "${file}" 2>/dev/null; then
    {
      echo ""
      echo "${content}"
    } >> "${file}"
  fi
}

ensure_safe_zshrc_defaults() {
  local zshrc="${HOME}/.zshrc"

  safe_append_once "${zshrc}" "# zoxide (devcontainer-managed)" '# zoxide (devcontainer-managed)
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init zsh)"'

  safe_append_once "${zshrc}" "# .NET global tools (devcontainer-managed)" '# .NET global tools (devcontainer-managed)
export PATH="$HOME/.dotnet/tools:$PATH"'

  safe_append_once "${zshrc}" "# zsh quality-of-life (devcontainer-managed)" '# zsh quality-of-life (devcontainer-managed)
[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f /usr/share/doc/fzf/examples/completion.zsh ] && source /usr/share/doc/fzf/examples/completion.zsh'
}

validate_zshrc_or_fallback() {
  local zshrc="${HOME}/.zshrc"
  local backup="${HOME}/.zshrc.pre-dotfiles.bak"

  if [[ ! -f "${zshrc}" ]]; then
    return 0
  fi

  # Run an interactive zsh startup test. If dotfiles expect missing tools/plugins,
  # this can fail with non-zero and we recover to a safe baseline.
  if ! ZDOTDIR="${HOME}" zsh -i -c 'exit 0' >/tmp/zshrc-check.log 2>&1; then
    log "Detected failing .zshrc startup; restoring safe fallback"
    if [[ -f "${backup}" ]]; then
      cp "${backup}" "${zshrc}"
      log "Restored previous .zshrc from backup"
    else
      cat > "${zshrc}" <<'EOF'
# Minimal safe zshrc (auto-generated by devcontainer sync)
export PATH="$HOME/.dotnet/tools:$PATH"
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init zsh)"
[ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f /usr/share/doc/fzf/examples/completion.zsh ] && source /usr/share/doc/fzf/examples/completion.zsh
EOF
      log "Wrote minimal safe .zshrc fallback"
    fi
  fi
}

# Clone/pull should never break container startup
if [[ ! -d "${DOTFILES_DIR}/.git" ]]; then
  log "Cloning ${DOTFILES_REPO} into ${DOTFILES_DIR}"
  if ! git clone --depth 1 "${DOTFILES_REPO}" "${DOTFILES_DIR}"; then
    log "Clone failed (network/auth). Continuing without dotfiles sync."
    ensure_safe_zshrc_defaults
    exit 0
  fi
else
  log "Updating ${DOTFILES_DIR}"
  git -C "${DOTFILES_DIR}" pull --ff-only --quiet || {
    log "Pull failed (non-fast-forward/network/auth). Skipping update this run."
  }
fi

apply_link() {
  local src="$1"
  local dest="$2"

  if [[ -f "${src}" ]]; then
    ln -sfn "${src}" "${dest}"
    log "Linked $(basename "${dest}")"
  else
    log "Skip $(basename "${dest}") (not found in repo)"
  fi
}

# Always apply tmux config
apply_link "${DOTFILES_DIR}/.tmux.conf" "${HOME}/.tmux.conf"

# Apply zsh config with backup/fallback protection
if [[ -f "${HOME}/.zshrc" && ! -L "${HOME}/.zshrc" ]]; then
  cp "${HOME}/.zshrc" "${HOME}/.zshrc.pre-dotfiles.bak" || true
fi
apply_link "${DOTFILES_DIR}/.zshrc" "${HOME}/.zshrc"

# Optional ash config (if you add it later)
apply_link "${DOTFILES_DIR}/.ashrc" "${HOME}/.ashrc"

# Add safe guards/idempotent defaults and validate
ensure_safe_zshrc_defaults
validate_zshrc_or_fallback

log "Done"
